# name: caw_interlinting
# on: [push, pull_request]
# jobs:
#   run-linters:
#     name: Run linters
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2
#         with:
#           # Full git history is needed to get a proper list of changed files within `super-linter`
#           fetch-depth: 0

#       - name: Lint Code Base
#         uses: github/super-linter@v3
#         env:
#           VALIDATE_ALL_CODEBASE: false
#           DEFAULT_BRANCH: master
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2
#       # ESLint and Prettier must be in `package.json`
#       - name: Run linters
#         uses: wearerequired/super-linter@v3
#         with:
#           eslint: true
#           prettier: true

#       - uses: actions/checkout@v1
#       - uses: actions-hub/stylelint@master
#         env:
#           PATTERN: '**.css'
#           INDENT_SPACES: 4
---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on: [push, pull_request]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
